{
 "title": "Vertica Performance Dashboard",
 "description": "Performance metrics for Vertica",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "vertica-grafana-datasource" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "<img src=\"https://www.vertica.com/wp-content/uploads/2023/01/Vertica-OT-White.png\"/>"
   },
   "targets": [
    {
     "rawSql": "SELECT \n$__time(end_time), \naverage_cpu_usage_percent \nFROM \nv_monitor.cpu_usage \nWHERE \n$__timeFilter(end_time)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 18, "x": 4, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n$__time(end_time), \naverage_cpu_usage_percent \nFROM \nv_monitor.cpu_usage \nWHERE \n$__timeFilter(end_time)"
    }
   ]
  },
  {
   "title": "Network KB/sec",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 4, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n$__time(end_time), \nNET_RX_KBYTES_PER_SECOND as \"rx\",  NET_TX_KBYTES_PER_SECOND as \"tx\"\nFROM \nv_monitor.SYSTEM_RESOURCE_USAGE \nWHERE \n$__timeFilter(end_time)\norder by end_time"
    }
   ]
  },
  {
   "title": "IO Usage KB/s",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 11, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n$__time(end_time), \nIO_READ_KBYTES_PER_SECOND as \"read\",  IO_written_KBYTES_PER_SECOND as \"write\"\nFROM \nv_monitor.SYSTEM_RESOURCE_USAGE \nWHERE \n$__timeFilter(end_time)\norder by end_time"
    }
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 18, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n$__time(end_time), \nAVERAGE_MEMORY_USAGE_PERCENT\nFROM \nv_monitor.SYSTEM_RESOURCE_USAGE \nWHERE \n$__timeFilter(end_time)\norder by end_time"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n$__time(end_time), \naverage_cpu_usage_percent \nFROM \nv_monitor.cpu_usage \nWHERE \n$__timeFilter(end_time)"
    }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n$__time(end_time), \naverage_cpu_usage_percent \nFROM \nv_monitor.cpu_usage \nWHERE \n$__timeFilter(end_time)\norder by end_time",
     "schema": "select schema"
    }
   ]
  },
  {
   "title": "IO Usage (read/write)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n$__time(end_time), \nIO_READ_KBYTES_PER_SECOND,  IO_written_KBYTES_PER_SECOND\nFROM \nv_monitor.SYSTEM_RESOURCE_USAGE \nWHERE \n$__timeFilter(end_time)\norder by end_time"
    }
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n$__time(end_time), \nAVERAGE_MEMORY_USAGE_PERCENT\nFROM \nv_monitor.SYSTEM_RESOURCE_USAGE \nWHERE \n$__timeFilter(end_time)\norder by end_time",
     "schema": "select schema"
    }
   ]
  },
  {
   "title": "Network (rx/tx)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n$__time(end_time), \nNET_RX_KBYTES_PER_SECOND,  NET_TX_KBYTES_PER_SECOND\nFROM \nv_monitor.SYSTEM_RESOURCE_USAGE \nWHERE \n$__timeFilter(end_time)\norder by end_time"
    }
   ]
  },
  {
   "title": "Error Messages",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "select event_timestamp as time,  user_name, error_level, error_code, message from v_monitor.error_messages order by 1 desc limit 10"
    }
   ]
  },
  {
   "title": "SQL Statements",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 23 },
   "targets": [
    {
     "rawSql": "select transaction_start as time,  user_name, current_statement from v_monitor.sessions order by 1 desc limit 10"
    }
   ]
  }
 ]
}